config/routes.rb
Rails.application.routes.draw do
  resources :animals
  root 'animals#index'
  get 'search' => 'sightings#index'
  resources :sightings do
    get :get_cal, on: :collection
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :sightings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  belongs_to :animal
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]
  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
    @animals_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:common_name, :latin_name, :kingdom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]
  def get_cal
    @sightings = Sighting.all
    events = []
    @sightings.each do |sighting|
      events << { id: sighting.id, date: sighting.date, title: sighting.animal.common_name, url: Rails.application.routes.url_helpers.sighting_path(sighting.id)}
    end
    render :json => events.to_json
  end

  # GET /sightings
  # GET /sightings.json
  def index
    @region = ['Swamp', 'Valley', 'Hills', 'Forest']
    if params[:start_date] == '' && params[:end_date] == '' && params[:region] == ''
      @sightings = Sighting.all
    elsif params[:region] == '' && params[:start_date].present? && params[:end_date].present?
      @sightings = Sighting.where(date: params[:start_date]..params[:end_date])
    elsif params[:start_date] == '' && params[:end_date] == '' && params[:region].present?
      @sightings = Sighting.where(region: params[:region])
    else
      @sightings = Sighting.where(date: params[:start_date]..params[:end_date], region: params[:region])
    end
  end #ends index

  # GET /sightings/1
  # GET /sightings/1.json
  def show
  end

  # GET /sightings/new
  def new
    @sighting = Sighting.new
    @region = ['Swamp', 'Valley', 'Hills', 'Forest']
    if params[:animal].nil?
      @sighting.animal = Animal.id
    else
      @sighting.animal = Animal.find(params[:animal])
    end

    @animals_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end

    @region_for_select = @region.map do |region|
      [region, region]
    end
  end

  # GET /sightings/1/edit
  def edit
    @region = ['Swamp', 'Valley', 'Hills', 'Forest']
    @region_for_select = @region.map do |region|
      [region, region]
    end

    @animals_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end

  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(sighting_params)
    @region = ['Swamp', 'Valley', 'Hills', 'Forest']
    @region_for_select = @region.map do |region|
      [region, region]
    end

    @animals_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:date, :region, :animal_id)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :animal_id %>
    <%= form.text_field :common_name, id: :animal_common_name %>
  </div>

  <div class="field">
    <%= form.label :latin_name %>
    <%= form.text_field :latin_name, id: :animal_latin_name %>
  </div>

  <div class="field">
    <%= form.label :kingdom %>
    <%= form.text_field :kingdom, id: :animal_kingdom %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals</h1>

<table>
  <thead>
    <tr>
      <th>Common name</th>
      <th>Latin name</th>
      <th>Kingdom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="animals_list">
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.common_name %></td>
        <td><%= animal.latin_name %></td>
        <td><%= animal.kingdom %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Animal', new_animal_path %>
<hr>
<h2>Add New Animal</h2>
<p>
  <!-- Input area for new animal -->
  <div class="field">
    <label for="animal_common_name">Common Name</label><br>
    <input type="text" name="animals[common_name]" id="animal_common_name" required>
  </div>

  <div class="field">
    <label for="animal_latin_name">Latin Name</label><br>
    <input type="text" name="animals[latin_name]" id="animal_latin_name" required>
  </div>

  <div class="field">
    <label for="animal_kingdom">Kingdom</label><br>
    <input type="text" name="animals[kingdom]" id="animal_kingdom" required>
  </div>

  <input type="hidden" name="animals[animal_id]" id="animal_id" value="<%=@animals.last.id%>"/><br>
  <button id="add_new_animal_button">Add New Animal</button>
</p>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<h1>Show Animals Page</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Common Name:</strong>
  <%= @animal.common_name %>
</p>

<p>
  <strong>Latin Name:</strong>
  <%= @animal.latin_name %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @animal.kingdom %>
</p>

<p>
  <strong>Sightings:</strong>
  <ul>
    <%= render partial: "sightings/sighting", collection: @animal.sightings %>
  </ul>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %> |
<%#= link_to 'New Sighting', new_sighting_path(:animal => @animal.id) %>
<%= link_to 'Search Sightings', sightings_path %>

<hr>
<h2>Add New Sighting</h2>
<p>
  <!-- Input area for new sighting -->
  <div class="field">
    <label for="sighting_date">Date</label><br>
    <input type="text" name="sighting[date]" id="sighting_date" required>
  </div>

  <div class="field">
    <label for="sighting_region">Region</label><br>
    <input type="text" name="sighting[region]" id="sighting_region" required>
  </div>

  <input type="hidden" name="sighting[animal_id]" id="lolz" value="<%=@animal.id%>"/><br>
  <button id="add_new_sighting_button">Add New Sighting</button>
</p>

<div id="calendar">
</div> <!--closes calendar div-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wildlife</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag  'jquery', 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/_form.html.erb
<%= form_with(model: sighting, local: true) do |form| %>
  <% if sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :sighting_date %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= select(:sighting, :region, @region_for_select) %>
  </div>

  <div class="field">
    <%= form.label :animal_id %>
    <%= select(:sighting, :animal_id, @animals_for_select) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sightings/_sighting.html.erb
<table id="sightings_list">

<tr>
  <td><%= sighting.date %> <%= sighting.region %></td>
</tr>
</table>

app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form', sighting: @sighting %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<body>
<p id="notice"><%= notice %></p>
<div id="title">
  <h1>Animal Sightings!</h1>
</div>
<div class="container">
  <div id="linkto">
    <%= link_to 'Animals Home Page', animals_url %>
  </div>

  <div id="form">
    <form action="search" method="get">
      <div id="text">
      <label for="start_date">Start date</label>
      <input id="start_date" name="start_date" type="text">
      <label for="end_date">End date</label>
      <input id="end_date" name="end_date" type="text"><br>
  <div id="boxes">
      <label for="region">Region</label>
     <select id="region" name="region" >
        <option value="Swamp">Swamp</option>
        <option value="Valley">Valley</option>
        <option value="Hills">Hills</option>
        <option value="Forest">Forest</option>
      </select><br><br>
      <button>Run Report</button>
    </div>
    </form>
  </div>

<div id="table">

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Region</th>
      <th>Animal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id ="body">
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.date %></td>
        <td><%= sighting.region %></td>
        <td><%= sighting.animal.common_name %></td>
    <% end %>
  </tbody>
</table>
</div>

  <!-- <div>
    <div style="height: 100px; width: 100px; background-color: black;">
  1
    </div>
    <div style="height: 100px; width: 100px; background-color: black;">
  2
    </div>
    <div style="height: 100px; width: 100px; background-color: black;">
  3
    </div>
    <div style="height: 100px; width: 100px; background-color: black;">
  4
    </div>
    <div style="height: 100px; width: 100px; background-color: black;">
  5
    </div>
  </div> -->
</div>

</body>

app/views/sightings/new.html.erb
<h1>New Sighting</h1>

<%= render 'form', sighting: @sighting %>

<%= link_to 'Back', animals_path %>

app/views/sightings/search.html.erb
 <table>
  <thead>
    <tr>
      <th>The New Animal Sightings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.date %></td>
        <td><%= sighting.common_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Animals Home', animals_url %>

app/views/sightings/show.html.erb
<h1>Show Sightings Page</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sighting.date %>
</p>

<p>
  <strong>Region:</strong>
  <%= @sighting.region %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @sighting.animal.common_name %>
</p>


<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', animals_path %>